---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "repositories": ["DiegoTc/guest-book-js-docker"],
      "dryRun" : "false",
      "branchConcurrentLimit": 6,
      "timezone": "America/Knox_IN",
      "schedule": ["after 8am every weekday", "before 10pm every weekday"],
      "enabledManagers": ["kubernetes"],
      "enabled": true,
      "logFormat": "json",
      "baseBranches": ["main"],
      "$schema": "https://docs.renovatebot.com/renovate-schema.json",
      "labels": ["renovate"],
      "kubernetes": {
        "fileMatch": ["^argo/.*\\.yaml$"]
      },
        "packageRules": [{
        "matchDatasources": ["docker"],
        "matchPackageNames": ["diegotc\/guestbook"],
        "extractVersion": "\d*-\d*$"
        "versioning": "regex:\d*-\d*$"
      }]
    }

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
spec:
  schedule: '*/3 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: renovate/renovate:35.14.4
              name: renovate-bot
              envFrom:
                - secretRef:
                    name: dockerhub
                - secretRef:
                    name: github
              env: # For illustration purposes, please use secrets.
                - name: RENOVATE_PLATFORM
                  value: 'github'
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: github
                      key: token
                - name: RENOVATE_AUTODISCOVER
                  value: 'false'
                - name: RENOVATE_BASE_DIR
                  value: '/tmp/renovate/'
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json'
                - name: LOG_LEVEL
                  value: debug
                - name: DOCKER_HUB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: dockerhub
                      key: password
                - name: DOCKER_HUB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: dockerhub
                      key: username
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
